### ISSUE TITLE
first pypi release

### ISSUE THREAD

**Issue by rupertford** [rupertford/melody#22]
Once #14 is on master I will make a first release on pypi.
I could add testing for 2.6, 3.2 etc, or perhaps leave that for another day.
I will need to create an initial changelog.
I could link pypi releases with GitHub tags, rather than releasing manually.
If so, I should probably make sure that readthedocs gets automatically updated at the same time.
Should I provide documentation within the release?

**Comment by jimboid** [comment]
I've been reading into documentation and did come across this http://read-the-docs.readthedocs.io/en/latest/getting_started.html it looks like it is using some kind of sphinx autobuilder. So I'm not sure if this somehow hooks into the distutils or something. 

But it looks as if near the bottom they suggest you can do it by commit. Not sure though how this would look on the readthedocs site if you started doing this on dev branches, in my case I would try to have it do this for things that hit master (my release tag branch), not sure what you would do though.

Is there a way to automate pushes to pypi based on tags? That is interesting, I might pinch that for some of my codes, is that using heroku?

**Comment by rupertford** [comment]
Yes, read-the-docs builds your sphinx documentation and uses its own styling. It looks like it automatically supports multiple versions of documentation if you tag with a version number, so it should be easy to do what I want, see ... http://docs.readthedocs.io/en/latest/versions.html

Yes, you can apparently push to pypi when a new tag is created using travis, see here ...
https://docs.travis-ci.com/user/deployment/pypi/.

**Comment by rupertford** [comment]
In terms of hooks with read-the-docs. I think it looks nightly by default but you can add it under web hooks so it updates on a particular trigger - in this case, a new tag or a merge to trunk I guess.

**Comment by jimboid** [comment]
That is pretty cool. I had no idea this could be done. You are going to save yourself a lot hassle here.

Thanks for the tips!

**Comment by rupertford** [comment]
documentation is now built automatically on readthedocs. This was pretty much as simple as setting up an account and pointing it at the repository. If the repository appears then you seem to get the webhooks automatically added. If not (e.g. it is an STFC project) then you have to add them manually - or at least I did. If you have your own style set up in sphinx then readthedocs will use that. I prefer their style so removed any style in the sphinx conf.py file. You get a latest and a stable and can change which you see by default. There is something not quite right with the indexing as I am getting an empty index but when built locally I don't. I've removed the index for the moment as it was not particularly useful in any case.

I've just tested melody manually on testpypi and it uploaded and subsequently installed OK.
`> python setup.py register -r pypitest`
`> python setup.py sdist upload -r pypitest`
`> cd`
`> python`
`>>> import melody`
`[error]`
`> sudo pip install -i https://testpypi.python.org/pypi melody`
`> python`
`>>> import melody`
`> sudo pip uninstall melody`
`> python`
`>>> import melody`
`[error]`

**Comment by rupertford** [comment]
I added a changelog. I first used the following tool https://github.com/skywinder/github-changelog-generator  but then edited the resultant output quite drastically afterwards.

**Comment by rupertford** [comment]
I edited the travis script as suggested so that (in theory) travis would create a release on pypi when I create a new tagged version. This included creating an encrypted version of my pypi password.

I then created a 0.1.0 tag. I went for a heavyweight tag and then pushed the tag.

GitHub has picked this up and created a new release for me.

readthedocs said it had created a stable version but it did not appear for me (perhaps I had a cached version?). When I manually rebuilt it worked. I've now made stable the default. Note, I thought it would call the version 0.1.0 but it seems to create its own branch so we lose the version number in the documentation.

travis has not automatically deployed the release onto pypi. I am about to see if I can work out why.

**Comment by jimboid** [comment]
> travis has not automatically deployed the release onto pypi. I am about to see if I can work out why.

Looking on pypi I can't see melody on there at all. So  do you think that it is somehow not calling the 

python setup.py register -r pypi

and simply trying to call the distribution

python setup.py sdist upload -r pypi

Looking in the logs on travis I don't see anything to do with registering a new version (you have to do this for each version upload).

**Comment by arporter** [comment]
>     travis has not automatically deployed the release onto pypi. I am
>     about to see if I can work out why.
>
> Looking on pypi I can't see melody on there at all. So do you think that
> it is somehow not calling the
>
> python setup.py register -r pypi
>
> and simply trying to call the distribution
>
> python setup.py sdist upload -r pypi
>
> Looking in the logs on travis I don't see anything to do with
> registering a new version (you have to do this for each version upload).
>
When I tried this for fparser on the pypi test-server 
(https://github.com/stfc/fparser/issues/11) it got as far as attempting 
to deploy and then failing because the version clashed with the version 
I'd already put on there. I'd previously registered the package but 
hadn't tried registering a new version.

God bless,

Andy.

-- 
Dr. Andrew Porter
The Hartree Centre
STFC Daresbury Laboratory
Keckwick Lane
Daresbury
WA4 4AD
Tel. : +44 (0)1925 603607
email: andrew.porter@stfc.ac.uk

**Comment by rupertford** [comment]
Thanks for the feedback. As James suggested it was failing as melody had not been registered with pypi at all. I registered with pypi then reran the travis job (68) and it deployed successfully.

A few observations. 1) it would be useful for travis to say that it failed here rather than report success! 2) it looks like travis will upload documentation to pypi for you but that this is switched off somehow (see travis log). I might look into this at some point. 3) The title of the travis job is misleading. I would expect it to say tag 0.1.0 push or something similar but it uses the previous log as the title.

I suspect that now I have a version of melody on pypi that next time the deploy will just work. I would be surprised if I have to manually register for each new release but that will be tested soon as the documentation is now out of date so I will update the documentation and push a new tag to see what happens.

**Comment by jimboid** [comment]
As long as the line:

python setup.py register -r pypi

gets called by travis before the actual upload and that you have changed your version number in setup.py then all should run smoothly with new versions. Otherwise you might get unwanted side effects such as the latest version always going under v0.1.0, only way to know for sure is to wait and try it.

**Comment by rupertford** [comment]
I think it throws a wobbler if you try to upload over an existing version. Anyway, I agree I'll try it and see. I'm going to close this ticket as I think it's pretty much been done.
