### ISSUE TITLE
Make code pep8 and (mostly) pylint compliant

### ISSUE THREAD

**Issue by rupertford** [rupertford/melody#5]
I've left out docstrings and not done proper pep8 tests up to now so need to improve the code.

**Comment by rupertford** [comment]
Created a code-quality branch

**Comment by jimboid** [comment]
Have you taken a look at some of the settings in landscape? You can improve its ability to point out things like white-space by doing something like this with a .landscape.yml

```
doc-warnings: true
test-warnings: false
strictness: veryhigh
python-targets:
  - 2
  - 3
```

doc-warnings will warn about bad docstrings, test-warnings toggles whether the unit tests are tested or ignored. You might not need both python versions as targets.

Be warned though if you set the strictness like this it will throw up lots more stuff (usually).

**Comment by rupertford** [comment]
pull request #13 has been merged to Master making the code pep8 and mostly pylint compliant. I am closing this issue but James has a good point. It would be good to up the anti with landscape checks. I have created a new issue #15 to do this.
